# Generated by Django 2.2.5 on 2020-07-20 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='Autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='Data_Publikacji',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='Data_Utworzenia',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='test',
            new_name='Treść',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Tytuł_Rozwiązania',
        ),
    ]
