# Generated by Django 2.2.5 on 2020-07-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Zatwierdzony_Komentarz',
            new_name='approved_comment',
        ),
    ]
